"""Standard cards data (20 Karten) für das Grunddeck von Merithra.

Diese Daten werden vom CardRegistry als eingebetteter Fallback verwendet,
wenn keine externen JSON-Dateien geladen werden können.
"""

from typing import Any, List


DEFAULT_CARDS_JSON: List[dict[str, Any]] = [
    # --- Freie Neutrale Minions (Start) ---
    {
        "id": "card_001",
        "name": "Großer Wolf",
        "cost": 1,
        "card_type": "MINION",
        "class_type": "NEUTRAL",
        "rarity": "FREE",
        "text": "Ein treuer Begleiter.",
        "attack": 1,
        "health": 1,
    },
    {
        "id": "card_002",
        "name": "Kleiner Affe",
        "cost": 1,
        "card_type": "MINION",
        "class_type": "NEUTRAL",
        "rarity": "FREE",
        "text": "Naschhaft und flink.",
        "attack": 1,
        "health": 2,
    },
    {
        "id": "card_003",
        "name": "Alter Weißscharte",
        "cost": 3,
        "card_type": "MINION",
        "class_type": "NEUTRAL",
        "rarity": "FREE",
        "text": "Erfahren und stark.",
        "attack": 3,
        "health": 2,
    },
    # --- Magier Karten ---
    {
        "id": "card_004",
        "name": "Feuerblitz",
        "cost": 1,
        "card_type": "SPELL",
        "class_type": "MAGE",
        "rarity": "COMMON",
        "text": "Fügt einem Ziel 1 Schaden zu.",
        "attack": 0,
        "health": 0,
        "effects": [{"type": "DAMAGE", "value": 1}],
    },
    {
        "id": "card_005",
        "name": "Feuerball",
        "cost": 2,
        "card_type": "SPELL",
        "class_type": "MAGE",
        "rarity": "COMMON",
        "text": "Fügt einem Ziel 3 Schaden zu.",
        "attack": 0,
        "health": 0,
        "effects": [{"type": "DAMAGE", "value": 3}],
    },
    {
        "id": "card_006",
        "name": "Magischer Schutz",
        "cost": 2,
        "card_type": "SPELL",
        "class_type": "MAGE",
        "rarity": "COMMON",
        "text": "Erhöht die Rüstung um 2.",
        "attack": 0,
        "health": 0,
        "effects": [{"type": "ARMOR", "value": 2}],
    },
    {
        "id": "card_007",
        "name": "Mondlichtelementar",
        "cost": 4,
        "card_type": "MINION",
        "class_type": "MAGE",
        "rarity": "RARE",
        "text": "Ein mächtiges Mana-Wesen.",
        "attack": 4,
        "health": 2,
    },
    {
        "id": "card_020",
        "name": "Flammenzauber",
        "cost": 4,
        "card_type": "SPELL",
        "class_type": "MAGE",
        "rarity": "LEGENDARY",
        "text": "Verheerender Feuerschaden.",
        "attack": 0,
        "health": 0,
        "effects": [{"type": "DAMAGE", "value": 5}],
    },
    # --- Krieger Karten ---
    {
        "id": "card_008",
        "name": "Sturmhammer",
        "cost": 3,
        "card_type": "WEAPON",
        "class_type": "WARRIOR",
        "rarity": "COMMON",
        "text": "Eine schwere Kampfaxt.",
        "attack": 3,
        "health": 0,
        "durability": 2,
    },
    {
        "id": "card_009",
        "name": "Schlachtruf",
        "cost": 3,
        "card_type": "SPELL",
        "class_type": "WARRIOR",
        "rarity": "COMMON",
        "text": "Alle eigenen Minionen erhalten +2 Angriff.",
        "attack": 0,
        "health": 0,
        "effects": [{"type": "SET_ATTACK", "value": 2}],
    },
    {
        "id": "card_010",
        "name": "Stärke trinken",
        "cost": 2,
        "card_type": "SPELL",
        "class_type": "WARRIOR",
        "rarity": "RARE",
        "text": "Heilt 4 Lebenspunkte.",
        "attack": 0,
        "health": 0,
        "effects": [{"type": "HEAL", "value": 4}],
    },
    {
        "id": "card_013",
        "name": "Sturmfaust",
        "cost": 5,
        "card_type": "MINION",
        "class_type": "WARRIOR",
        "rarity": "RARE",
        "text": "Unbändige Zerstörungskraft.",
        "attack": 5,
        "health": 4,
    },
    {
        "id": "card_011",
        "name": "Riesenschreck",
        "cost": 7,
        "card_type": "MINION",
        "class_type": "WARRIOR",
        "rarity": "EPIC",
        "text": "Ein Schrecken auf dem Schlachtfeld.",
        "attack": 7,
        "health": 5,
    },
    {
        "id": "card_012",
        "name": "Heldendunkelheit",
        "cost": 10,
        "card_type": "HERO_POWER",
        "class_type": "WARRIOR",
        "rarity": "LEGENDARY",
        "text": "Die legendäre Heldenmacht.",
        "attack": 0,
        "health": 0,
    },
    # --- Neutrale Spezialkarten ---
    {
        "id": "card_014",
        "name": "Stille",
        "cost": 2,
        "card_type": "SPELL",
        "class_type": "NEUTRAL",
        "rarity": "RARE",
        "text": "Entfernt alle Effekte von einem Ziel.",
        "attack": 0,
        "health": 0,
    },
    {
        "id": "card_015",
        "name": "Wüstenviper",
        "cost": 4,
        "card_type": "MINION",
        "class_type": "NEUTRAL",
        "rarity": "EPIC",
        "text": "Listig und gefährlich.",
        "attack": 4,
        "health": 3,
    },
    {
        "id": "card_016",
        "name": "Scharfschütze",
        "cost": 3,
        "card_type": "MINION",
        "class_type": "NEUTRAL",
        "rarity": "COMMON",
        "text": "Kann sofort angreifen.",
        "attack": 3,
        "health": 1,
        "keywords": ["CHARGE"],
    },
    {
        "id": "card_017",
        "name": "Wachposten",
        "cost": 1,
        "card_type": "MINION",
        "class_type": "NEUTRAL",
        "rarity": "COMMON",
        "text": "Schützt andere Minionen.",
        "attack": 1,
        "health": 2,
        "keywords": ["TAUNT"],
    },
    {
        "id": "card_018",
        "name": "Mühevolle Reise",
        "cost": 1,
        "card_type": "SPELL",
        "class_type": "NEUTRAL",
        "rarity": "COMMON",
        "text": "Ziehe eine Karte.",
        "attack": 0,
        "health": 0,
        "effects": [{"type": "DRAW_CARDS", "value": 1}],
    },
    {
        "id": "card_019",
        "name": "Kriegerin der Schlacht",
        "cost": 6,
        "card_type": "MINION",
        "class_type": "NEUTRAL",
        "rarity": "LEGENDARY",
        "text": "Eine unbesiegbare Kriegerin.",
        "attack": 6,
        "health": 5,
        "keywords": ["TAUNT", "CHARGE"],
    },
]
